### ISSUE TITLE
Tshock world location issue?

### ISSUE THREAD

**Issue by gelir95** [beardedio/terraria#17]
Creating a world with 

sudo docker run --rm -it -p 7777:7777 \
-v $HOME/terraria/config:/config \
--name=terraria \
beardedio/terraria:tshock-dev-latest

does not create the world /root/terraria/config
the same without tshock does.

**Comment by RafaelSchridi** [comment]
Yeah i had the same issue and had to change the serverconfig default file location to /config

**Comment by hskrtich** [comment]
It looks like tshock change one of there command line vars. This has been fixed with the lastest code change. Thank you for reporting the issue.
