### ISSUE TITLE
More command line params

### ISSUE THREAD

**Issue by Chaoschaot232** [beardedio/terraria#18]
I have seen that there are more params are setable, which means, that world is not the only one.
There are cmds out like -steam/lobby/port/...

Could you add all of them so that they are setable as env? This would safe a lot of time incl. to provide an edited serverconfig.txt :)

**Comment by Nightreaver** [comment]
If you add the serverconfig as volume, you can have it editable from the outside without changing the container

**Comment by hskrtich** [comment]
I just pushed an update that will allow you to pass in what ever commands you want to the server. 

It can be added to the end of the docker run command like this

`docker run -it -v $HOME/terraria/tshock:/config -e world=test.wld beardedio/terraria:tshock-4.4.0-pre11 "-port 12345"`
