### ISSUE TITLE
Error starting server (v1.4.0.5)

### ISSUE THREAD

**Issue by AustinMcPhail** [beardedio/terraria#20]
Hey there, updated pulled the latest image and went to run the server using all of the same setting as 1.4.0.4, and now the server crashes when loading the world.

I've copied the world out and loading it into 1.4.0.5 in single player. The world loads fine, so it's not corrupted, or at least I'm pretty certain it isn't. I've changed the path to the absolute path of the world file on my server, but that obviously  didn't work, however I got the error that the world could not be found, so that just reaffirmed that I had the path right to begin with.

Saw some other notes online about the Terraria binary failing to read the config file correctly, but haven't had luck with adding any missing details. Due to the container crashing, I'm unable to have enough time to grab the crashlog.txt as well (If I'm just naive to how to prevent this, let me know please!).

I'm using Portainer to manage the container. I'm able to generate brand new worlds with the 1.4.0.5 image and it doesn't complain.

I will also admit, there was a power outage, which is why the server was down in the first place. I figured I'd just update it. I booted the server back up, had it running 1.4.0.4, attached and saved the world manually (which is bound to a folder on my disk), and pulled the latest image. That was when I began getting the error.

Config: https://pastebin.com/3HkjEiAj
Logged Error:
```
Starting container, CMD: ./TerrariaServer -x64 -config /config/serverconfig.txt -banlist /config/banlist.txt -world /config/Lucky_Harbor_of_Mangos.wld ./run.sh
﻿﻿﻿﻿Error Logging Enabled.
]0;Terraria Server v1.4.0.5Terraria Server v1.4.0.5
Server crash: 6/10/2020 6:18:34 AM
System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.Main.WriteFancyWorldLoadErrorToConsole () [0x00005] in <0ebea07e9a804a06a9f1dd17904b9c9c>:0 
  at Terraria.Main.DedServ () [0x00b21] in <0ebea07e9a804a06a9f1dd17904b9c9c>:0 
  at Terraria.Program.LaunchGame (System.String[] args, System.Boolean monoArgs) [0x000ac] in <0ebea07e9a804a06a9f1dd17904b9c9c>:0 

Please send crashlog.txt to support@terraria.org
```

**Comment by AustinMcPhail** [comment]
Upon further searching, it seems that I'm not the only one affected and it could actually be an issue with the binary itself. However it might not be. There is no rush, I can always run the world from my machine instead of going dedicated for now, but I still figured I'd bring this to your attention. Thanks for any investigation you do, time willing!

More info: https://forums.terraria.org/index.php?threads/terraria-server-1-4-0-5-world-generation-crash.93411/

**Comment by hskrtich** [comment]
@AustinMcPhail Can you provide the command or the config file you are using to start the server?

**Comment by AustinMcPhail** [comment]
@bskrtich 
serverconfig.txt: https://pastebin.com/3HkjEiAj

`CMD: ./TerrariaServer -x64 -config /config/serverconfig.txt -banlist /config/banlist.txt -world /config/Lucky_Harbor_of_Mangos.wld ./run.sh`

**Comment by hskrtich** [comment]
@AustinMcPhail Sorry I mean I need to see the config in Portainer

**Comment by AustinMcPhail** [comment]
@bskrtich 
Okay for sure. Hopefully screenshot is okay, if not just hit me back and I can give you any other details. If you end up wanting the world, I'm happy to provide that as well.

![Capture](https://user-images.githubusercontent.com/5369192/84401867-03434700-abc1-11ea-8315-abc893aecc69.PNG)

**Comment by hskrtich** [comment]
You need to remove the CMD and you need to enable "interactive"

**Comment by AustinMcPhail** [comment]
Missed some configs. Already is interactive.
![Capture](https://user-images.githubusercontent.com/5369192/84403757-4a323c00-abc3-11ea-9033-078e20095deb.PNG)

You suggest removing that CMD and giving it a try?

**Comment by AustinMcPhail** [comment]
@bskrtich YO! That was absolutely it. Dropped that CMD and it loaded just fine. You're a gem. That was something Portainer actually put there by default!

**Comment by hskrtich** [comment]
Cool Im glad that worked.

**Comment by AndyLee1024** [comment]
Hi, how can i enable interactive console in terminal ?
