### ISSUE TITLE
Support for 1.4.3

### ISSUE THREAD

**Issue by LilVapers** [beardedio/terraria#36]
Just wondering if you will be adding support for 1.4.3.

**Comment by Velocitas77** [comment]
me2

**Comment by RafaelSchridi** [comment]
https://github.com/beardedio/terraria/pull/37

**Comment by mje-nz** [comment]
I built #37 and pushed it to mjenz/terraria:1.4.3, feel free to try that while you wait

**Comment by Velocitas77** [comment]
Where can I try out your version of this build? I am still new gitlab handling.

**Comment by jonjonjapon** [comment]
1.4.3.1 has actually been released, this commit may need to be updated as well. Ryshe is currently supporting 1.4.3 but is yet to accept a 1.4.3.1 pull request.

**Comment by Wolnos** [comment]
#37 has been updated to 1.4.3.1

**Comment by mje-nz** [comment]
Thanks @Wolnos, I've pushed that to mjenz/terraria:1.4.3.1

**Comment by Velocitas77** [comment]
Thank you! Now we are talking about 1.4.3.2 lol.

**Comment by Wolnos** [comment]
#37 has been updated

**Comment by mje-nz** [comment]
Pushed to mjenz/terraria:1.4.3.2

**Comment by hskrtich** [comment]
I have updated the repo and pushed new images. Please open up a new ticket if anyone has any problems
