### ISSUE TITLE
mono:slim?

### ISSUE THREAD

**Issue by mattlorimor** [beardedio/terraria#5]
In the interest of slimming down the image sizes, would you be open to a PR that migrates all the `FROM mono` to `FROM mono:slim`? Doing so results in an image that's roughly `463 MB` smaller.

The only package that I saw that needed to be manually installed after migrating to `mono:slim` is `curl`.

**Comment by hskrtich** [comment]
Good idea, I will try this on my end and see what I can find out

**Comment by mattlorimor** [comment]
@bskrtich - If you're looking to implement it on your end, tshock also required `nuget` (or a package it brings) to be installed: https://github.com/beardedio/terraria/pull/6#issuecomment-630399703.

**Comment by mattlorimor** [comment]
I'm not sure what the _actual_ packages required were.

**Comment by mattlorimor** [comment]
This was handled.
