### ISSUE TITLE
ERROR: Head "ghcr.io/v2/beardedio" Does not exist upon using docker compose

### ISSUE THREAD

**Issue by RavingSmurfGB** [beardedio/terraria#56]
Hi Team,

I have tried to use this today, but have no previous experience with it, I used docker compose via your hub.docker page.

However, when I try to compose I get this message
C:\docker_images>docker-compose up
Pulling terraria (ghcr.io/beardedio/terraria:latest)...
ERROR: Head "https://ghcr.io/v2/beardedio/terraria/manifests/latest": unauthorized

When I navigate to https://ghcr.io/beardedio/ I get a 404 error

Thank you for any help in advance and this looks like a great piece of work!

Also, this is my docker-compose file
    terraria:
      image: ghcr.io/beardedio/terraria:latest
      ports:
        - '7777:7777'
      restart: unless-stopped
      environment:
        - world=The_Abandoned_Vibe
      volumes:
        - C:\docker_images\terarria:/config
      tty: true
      stdin_open: true

**Comment by hskrtich** [comment]
Well I feel stupid, I have made the docker package public. Can you check if you can pull it now?

**Comment by RavingSmurfGB** [comment]
> Well I feel stupid, I have made the docker package public. Can you check if you can pull it now?

Hehe, its no problem :)

Seems to work perfectly now!

**Comment by hskrtich** [comment]
Awesome. Thanks for reporting and checking!
